"""add language to posts

Revision ID: 5bcffe2cebd6
Revises: 8cc9c4ebdc07
Create Date: 2020-08-10 15:38:30.348424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bcffe2cebd6'
down_revision = '8cc9c4ebdc07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('language', sa.String(length=5), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'language')
    # ### end Alembic commands ###
